//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiFruverSAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Pedido
    {
        public int Codigo { get; set; }
        public int Cantidad { get; set; }
        public Nullable<double> Descuento { get; set; }
        public double PrecioUnitario { get; set; }
        public double subtotal { get; set; }
        public double TotalPagar { get; set; }
        public Nullable<double> iva { get; set; }
        public int idProducto { get; set; }
        public int CodigoPedido { get; set; }
    
        public virtual tblPedido tblPedido { get; set; }
        public virtual tblProducto tblProducto { get; set; }
    }
}
