//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiFruverSAS.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class tblCliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCliente()
        {
            this.tblDireccionClientes = new HashSet<tblDireccionCliente>();
            this.tblPedidoes = new HashSet<tblPedido>();
            this.tblTelefonoClientes = new HashSet<tblTelefonoCliente>();
        }
    
        public int Codigo { get; set; }
        public int idTipoDoc { get; set; }
        public int idGenero { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public int NroDoc { get; set; }
        public Nullable<int> Tipo_Cliente { get; set; }
    
        public virtual tblGenero tblGenero { get; set; }
        public virtual tbltipoDoc tbltipoDoc { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDireccionCliente> tblDireccionClientes { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPedido> tblPedidoes { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTelefonoCliente> tblTelefonoClientes { get; set; }
    }
}
