//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiFruverSAS.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class tblDireccionCliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDireccionCliente()
        {
            this.tblPedido_Direc = new HashSet<tblPedido_Direc>();
        }
    
        public int Codigo { get; set; }
        public int idCliente { get; set; }
        public int idCuidad { get; set; }
        public string Direccion { get; set; }
        public bool Activo { get; set; }
    
        public virtual tblCliente tblCliente { get; set; }
        public virtual tblCuidad tblCuidad { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPedido_Direc> tblPedido_Direc { get; set; }
    }
}
