//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiFruverSAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmpleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEmpleado()
        {
            this.tblDireccionEmpleadoes = new HashSet<tblDireccionEmpleado>();
            this.tblTelefonoEmpleadoes = new HashSet<tblTelefonoEmpleado>();
            this.tblUsuarios = new HashSet<tblUsuario>();
        }
    
        public int Codigo { get; set; }
        public int idEmpleado { get; set; }
        public int NroDoc { get; set; }
        public int idGenero { get; set; }
        public int idCargo { get; set; }
        public int idTipoDoc { get; set; }
        public string fecha_Ingreso { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public double Salario { get; set; }
        public bool Activo { get; set; }
    
        public virtual tblCargo tblCargo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDireccionEmpleado> tblDireccionEmpleadoes { get; set; }
        public virtual tblGenero tblGenero { get; set; }
        public virtual tbltipoDoc tbltipoDoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTelefonoEmpleado> tblTelefonoEmpleadoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUsuario> tblUsuarios { get; set; }
    }
}
