//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiFruverSAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPedido()
        {
            this.Detalle_Pedido = new HashSet<Detalle_Pedido>();
            this.tblPedido_Direc = new HashSet<tblPedido_Direc>();
        }
    
        public int Numero_Pedido { get; set; }
        public System.DateTime Fecha_Pedido { get; set; }
        public System.DateTime Fecha_Entrega { get; set; }
        public bool Domicilio { get; set; }
        public int idProducto { get; set; }
        public int idCliente { get; set; }
        public int idUsuario { get; set; }
        public int idTipoVenta { get; set; }
        public int idFormaPago { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Pedido> Detalle_Pedido { get; set; }
        public virtual tblCliente tblCliente { get; set; }
        public virtual tblFormaDePago tblFormaDePago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPedido_Direc> tblPedido_Direc { get; set; }
        public virtual tblProducto tblProducto { get; set; }
        public virtual tblTipo_Venta tblTipo_Venta { get; set; }
        public virtual tblUsuario tblUsuario { get; set; }
    }
}
