//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiFruverSAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTelefonoEmpleado
    {
        public int Codigo { get; set; }
        public int NumTelefono { get; set; }
        public bool Activo { get; set; }
        public int idTipoTel { get; set; }
        public Nullable<int> idEmpleado { get; set; }
    
        public virtual tblEmpleado tblEmpleado { get; set; }
        public virtual tblTipoTel tblTipoTel { get; set; }
    }
}
